### ISSUE TITLE
"TypeError: Cannot read property 'push' of undefined"

### ISSUE THREAD

**Issue by Vinisz** [hotNipi/node-red-contrib-ui-level#13]
**Describe the bug**
When pressing "Deploy" in node red, "TypeError: Cannot read property 'push' of undefined" appears for all the contrib-ui-level nodes in the debug window

**To Reproduce**
Install new node-red system, install node-red-contrib-ui-level to the template, copy over the flow (via clipboard) from the old system, press "deploy"
There are no issues with any of the other nodes, pallete items and flows on the new system

**Expected behavior**
Normal Deploy, without the error, and the node showing up on the dashboard,

**Screenshots**

**Environment and versions (please complete the following information):**
 - OS: 4.14.98-v7+ (Raspberry PI 3b+)
 - Browser Chrome
 - Node-RED version 0.20.5
 - Dashboard version 2.15.0
 - ui-level version 0.0.20

**Additional context**
Add any other context about the problem here
.
Dashboard has just released a new version, maybe this is where the problem lies... I did not use this version on the older system (Synology NAS) and did not have any problems there.

**Comment by hotNipi** [comment]
Did the previous installation ( from where you copied the flow) had same version of ui-level?

**Comment by Vinisz** [comment]
Yes, same level

**Comment by hotNipi** [comment]
Issue does not reproduce for me but as I don't have PI or similar environment available I cant really be sure what is wrong. 
I kindly ask you  to do an experiment if you can.  To isolate issue, can you do most simple flow, Inject and level node only and see if it has same issue. 
And in addition if possible can you please share the broken flow json or part of it?

**Comment by Vinisz** [comment]
Sure, no problem... I created the flow and published it, got the same error on the new condifigured node.
Here is the flow :

`[{"id":"cdafba88.b729f8","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"73994967.3acb88","type":"inject","z":"cdafba88.b729f8","name":"","topic":"","payload":"40","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":120,"wires":[["5d4cb9b1.b0bf18"]]},{"id":"5d4cb9b1.b0bf18","type":"ui_level","z":"cdafba88.b729f8","group":"9c754c2e.de783","order":5,"width":0,"height":0,"name":"","label":"","colorHi":"#e60000","colorWarn":"#ff9900","colorNormal":"#00b33c","colorOff":"#595959","min":0,"max":100,"segWarn":"","segHigh":"","unit":"units","layout":"sh","channelA":"","channelB":"","decimals":0,"animations":"soft","shape":2,"colorschema":"fixed","x":410,"y":120,"wires":[]},{"id":"9c754c2e.de783","type":"ui_group","z":"","name":"Controller","tab":"239c8888.1dd628","order":1,"disp":true,"width":"6","collapse":false},{"id":"239c8888.1dd628","type":"ui_tab","z":"","name":"Systems","icon":"dashboard","order":9,"disabled":false,"hidden":false}]`

**Comment by Vinisz** [comment]
For your informatiom, just did a fresh docker install of node-red (latest) on synology , installed dashboard and ui-level (both latest versions) , result : same error

**Comment by hotNipi** [comment]
What is the version of node.js you are using?

**Comment by Vinisz** [comment]
a "node --version" command inside the docker container reports: v 8.15.1
Hope that this is what you are looking for ?
Oh, and on the raspberry PI it reports : v 10.15.3

**Comment by hotNipi** [comment]
Yep. Both should be fine. Digging deeper.

**Comment by juggledad** [comment]
I ran into this this morning on a Pi and then tried the same thing on my Mac which had no problem. Then I noticed the Pi was back on NR v0.19.5 and the dashboard was old. I upgraded everything and the issue went away.

**Comment by hotNipi** [comment]
Thank you for notification. Case closed
