### ISSUE TITLE
Dashboard tab change clears level bar

### ISSUE THREAD

**Issue by Gonzo4** [hotNipi/node-red-contrib-ui-level#15]
**Describe the bug**
If you change the dashboard tab the bar of the ui-level is empty, I think version 0.0.24 was OK?!

**To Reproduce**
Create a dashboard with 2 tabs with an ui-level node on each. Every time you change the tab the level bar is empty (text shows the correct value) until a new value is received...

**Expected behavior**
Bar is visible ;)

**Screenshots**

![2019-09-19 19_25_08-Node-RED Dashboard](https://user-images.githubusercontent.com/6013729/65266530-8a243100-db13-11e9-8b39-ab17c746acd8.png)

**Environment and versions (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Node-RED version 0.20.8
 - Dashboard version 2.16.3
 - ui-level version 0.1.3

**Comment by hotNipi** [comment]
Thank you for reporting. Fixed in version 0.1.4
