### ISSUE TITLE
Requirements Question

### ISSUE THREAD

**Issue by Digital-Thor** [hotNipi/node-red-contrib-ui-level#16]
Hello.  Thanks for this cool bar-graphing display for node-red!  I'm having some troubles getting it working.  I can see a bit of a scale and a number that changes to match my slider, but no segments of the bar-graph (see screenshot).  My system and startup info is below.  Any suggestions? 

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian

Node-RED version: v0.20.8
Node.js  version: v8.16.2
Linux 4.19.66-v7+ arm LE
Dashboard version 2.17.1 started at /ui
Context store  : 'default' [module=memory]

![image](https://user-images.githubusercontent.com/2617288/67138066-421c2b00-f1f3-11e9-96fe-24bfd77a0f62.png)

**Comment by Digital-Thor** [comment]
I figured out the problem.  It seems to be dependent on the dashboard "1x1 Widget Size".  This setting is found in the right side panel **dashboard** tab, with **Site** sub-tab.  The Node-Red default is 48 x 48.  Mine was at 24 x 24 for tighter layout purposes, but I'm okay with 48 x 48.  Working great now!

![image](https://user-images.githubusercontent.com/2617288/67154054-dea10480-f2a9-11e9-8835-b2bcbbcd0004.png)

**Comment by hotNipi** [comment]
That is actully something I should mention somehow at info page. I need to figure out minimum 1x1 widget size where it still working. 

Thank you for report.

**Comment by hotNipi** [comment]
Version 0.1.21 may be slightly better in terms of supporting smaller 1x1 unit sizes. There will be some disadvantages as you can not use intermediate ticks with single horizontal layout as there is not much space to place the value field then (or vice versa). But default works and you actually can take advantage of small widget sizes. I think that's all I can do about it.

**Comment by Digital-Thor** [comment]
Much better. Thank you @hotNipi.  Here's what it looks like at: 
- 24 x 24 widget size, as set in the site-config, and
- 10 x 3 units, as set in the ui-level's node-config.

![image](https://user-images.githubusercontent.com/2617288/67640923-d86ae380-f8ba-11e9-870a-cb3a1123e565.png)
