### ISSUE TITLE
got error to use Level and Value-trail

### ISSUE THREAD

**Issue by taijihagino** [hotNipi/node-red-contrib-ui-level#17]
I got errors "TypeError: Cannot read property 'push' of undefined" when using Level and Value-trail on IBM Cloud Node-RED.
Seems like not include "push" in payload.
Btw, it gets success to use the same node on standalone Node-RED...

error screen shots:
https://ibm.box.com/s/gmedhby5awa0uw4jwpgqdqy8c6gi8b9z
https://ibm.box.com/s/vayuhtzmu4we44dm5dql5nfi8kt5use9

**Comment by hotNipi** [comment]
Can you please update the issue description by adding versions in use.
nodejs
Node-RED
Dashboard
ui-level
value-trail

**Comment by taijihagino** [comment]
Sorry, I forgot to write the versions. These versions are below;

node.js (runtime on IBM Cloud): v10.16.0
Node-RED: v1.0.2
node-red-dashboard: v2.17.1
node-red-contrib-ui-level: v0.1.22
node-red-contrib-ui-value-trail: v0.1.3

**Comment by hotNipi** [comment]
Versions are up to date.
The issue seems to be known and there is solution.
Please read this topic https://discourse.nodered.org/t/troubleshooting-an-error-on-ibm-cloud/16877/9

**Comment by taijihagino** [comment]
Perfect! It has been solved, thanks!
