### ISSUE TITLE
ui-level resetting with deploy

### ISSUE THREAD

**Issue by Just-another-pleb** [hotNipi/node-red-contrib-ui-level#18]
I have `ui-level` on a dashboard.
It shows the value.

I modify ANOTHER node in the flow and do a `deploy` (modified nodes) and the node just shows 100%.

Details:
NR 1.0.3
Dashboard:  2.19.2
RPI Stretch
Also happens on Ubuntu 18.04 LTS

Screen shots:
After deploy

![Screenshot from 2019-12-17 19-50-59](https://user-images.githubusercontent.com/39888280/70980061-c4976d00-2106-11ea-8ff5-b4ac13f3b5f9.png)

After button pressed

![Screenshot from 2019-12-17 19-51-32](https://user-images.githubusercontent.com/39888280/70980137-e690ef80-2106-11ea-9e6b-9112c39ef2ae.png)

The flow:  (Picture)

![Screenshot from 2019-12-17 19-51-38](https://user-images.githubusercontent.com/39888280/70980198-06281800-2107-11ea-83ef-333e55c245dd.png)

**Comment by hotNipi** [comment]
True. will investigate tomorrow.

**Comment by hotNipi** [comment]
fixed in v0.1.23
