### ISSUE TITLE
Widget doesn't respect placement in dashboard layout tab

### ISSUE THREAD

**Issue by bohtho** [hotNipi/node-red-contrib-ui-level#2]
Widget doesn't respect placement in dashboard layout tab. The last level edited is always at the bottom and they don't respect being dragged to another placement in the layout list.

**Comment by hotNipi** [comment]
Known issue. As far the investigations done by now, it seems to be common issue for all custom ui-widgets and not produced by node itself but probably node-red-dashboard. Not sure exactly. Until not clear, I leave this issue open. Thank you.

**Comment by hotNipi** [comment]
Fixed in 0.0.10
