### ISSUE TITLE
It would be great if the UI_Level would auto scale with customer widget sizes

### ISSUE THREAD

**Issue by RichChism** [hotNipi/node-red-contrib-ui-level#21]
**Is your feature request related to a problem? Please describe.**
With the default widget size of 48x48 pixels the levels look great but when scaling to say 96x96 the level does not seem to scale with the specified widget size.   For example if you have a level set to a widgets size of 2x1 at 48x48 pixels it looks great but if you double the pixel resolution to 96x96 the level only fills half of the widgest defined space.

**Describe the solution you'd like**
It would be great if it auto scaled with the resolution.  in a very old version I think 0.2 it scaled correctly.

![image](https://user-images.githubusercontent.com/2258675/78051555-791a6f00-7343-11ea-880e-59c1e50f6496.png)

![image](https://user-images.githubusercontent.com/2258675/78051646-9d764b80-7343-11ea-8c01-2845888986f7.png)

![image](https://user-images.githubusercontent.com/2258675/78051727-ba128380-7343-11ea-9ed3-10dc1915ba0e.png)

![image](https://user-images.githubusercontent.com/2258675/78051778-ce568080-7343-11ea-958d-dc29fd0e0a94.png)

![image](https://user-images.githubusercontent.com/2258675/78051887-ee863f80-7343-11ea-9931-bb7cfc526b45.png)

**Comment by RichChism** [comment]
Issue is related to the Node-Red dashboard.  It is corrected when upgrading to the latest dashboard. Using the latest dashboard corrects the issue.

node-red-dashboard
from 2.14.0 to  2.19.4****

**Comment by hotNipi** [comment]
Known issue. It requires complete redesign.   A lot of work so no quick fix to expect. PR always welcome.

**Comment by hotNipi** [comment]
> Issue is related to the Node-Red dashboard. It is corrected when upgrading to the latest dashboard. Using the latest dashboard corrects the issue.
> 
> node-red-dashboard
> from 2.14.0 to 2.19.4****

This is ofcourse good news but really there is more than one size issues I have to address in some future. I must remember that there is actual users with double sized unit factor for dashboard layout.
