### ISSUE TITLE
No segments option.

### ISSUE THREAD

**Issue by Powertx** [hotNipi/node-red-contrib-ui-level#22]
**Is your feature request related to a problem? Please describe.**
Not really related to a problem.

**Describe the solution you'd like**
I would like, a setting to disable the segments, just continious line.
Would be cool, if you had an option, so that value field shows diffirent values, to the ones bargraph is using. (if that makes sense).

**Describe alternatives you've considered**
I cant find reasonable solutions.

**Additional context**
Im making a spotify controll, and wanted to add a progress bar for song, that is currently playing.

**Comment by hotNipi** [comment]
You can always configure all the colors to be same. (except the off color) 
For value field what you want to show then?

**Comment by Powertx** [comment]
I know i can configure colors to be all the same, but it would be a nice option, to disable spacing between segments. So it looks like one line.
I would like an option, so the text above the bargraph shows a diffirent value than the actual bargraph is updating to.

**Comment by hotNipi** [comment]
That will be absolutely different thing then. Check the node-red-contrib-artless-gauge for  non segmented line.
But even then - to show something else than value in value field will not be possible. It just does not make any sense to have such functionality built in.
