### ISSUE TITLE
Horizontal Level always displayed as "Max" - again

### ISSUE THREAD

**Issue by gerhard1951** [hotNipi/node-red-contrib-ui-level#23]
Hi,
until yesterday I was using node-red-contrib-ui-level without any trouble with an older version. Yesterday I updated to the latest version 0.1.27. After the update a new deployment was urged by all my ui-level nodes.
After having done so, I experienced, that depending on the browser type the level display worked correctly or not:
Firefox browser on my PC: Level display ok
Firefox browser on Android smartphone and tablet: Only "Max" is displayed on all level meters
Chrome browser on Andoid tablet: Level display ok.

Who has an idea how to eliminate the dependency of browser types?
Best regards
Gerhard

**Comment by hotNipi** [comment]
I have no problems with Android smartphone (Chrome, Brave, Firefox)
It may be needs some kind of cache clearing. (Clear private data)

**Comment by gerhard1951** [comment]
Unfortunately, cache (and other private data) clearing didn´t help.
Other ideas?

**Comment by gerhard1951** [comment]
Sorry, I closed the issue unintentionally instead of sending a comment.
Clearing the cache (and other private data) did not help.
Other ideas?

**Comment by hotNipi** [comment]
No currently. Can you debug the firefox on mobile device for any possible errors?
I know it is painfull and not always successful but if can try .. 
https://developer.mozilla.org/en-US/docs/Tools/about:debugging

**Comment by hotNipi** [comment]
Also, as it probably will take some more investigations:
How do you run the node red. (locally, cloud, docker ... )?
Do you remember what was previous (working) version of ui_level?
What is the versions of node red and the dashboard you are using?

**Comment by gerhard1951** [comment]
Debugging will need some time, but concerning your other questions.:

 

*	Node Red runs in a Raspbery Pi 3+
*	I cannot remember the old version of ui_level, but I loaded it into the palette on May 2019. Since this date I never made an update (because everything worked fine)


*	Node red versions:


*	15 May 14:13:38 - [info] Node-RED Version: v0.20.6
*	15 May 14:13:38 - [info] Node.js  Version: v10.20.1
*	15 May 14:13:38 - [info] Linux 4.19.97-v7+ arm LE
*	15 May 14:13:40 - [info] Paletten-Nodes werden geladen
*	15 May 14:13:47 - [info] Dashboard version 2.22.1 started at /ui
*	15 May 14:13:51 - [info] Einstellungsdatei: /home/pi/.node-red/settings.js
*	15 May 14:13:51 - [info] Kontextspeicher: 'default' [ module=memory]
*	15 May 14:13:51 - [info] Benutzerverzeichnis: /home/pi/.node-red
*	15 May 14:13:51 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false




 

Von: hotNipi <notifications@github.com> 
Gesendet: Freitag, 15. Mai 2020 14:05
An: hotNipi/node-red-contrib-ui-level <node-red-contrib-ui-level@noreply.github.com>
Cc: gerhard1951 <mail@ge-benker.de>; State change <state_change@noreply.github.com>
Betreff: Re: [hotNipi/node-red-contrib-ui-level] Horizontal Level always displayed as "Max" - again (#23)

 

Also, as it probably will take some more investigations:
How do you run the node red. (locally, cloud, docker ... )?
Do you remember what was previous (working) version of ui_level?
What is the versions of node red and the dashboard you are using?

**Comment by hotNipi** [comment]
Any good reason why not to update node-red to latest version?
v0.20.6 seems kind of old. Can't say if makes any difference according to current issue but ...

**Comment by hotNipi** [comment]
Ok, I did one update blindly. 0.1.28 will be shortly available..
Try and let me know..

**Comment by gerhard1951** [comment]
Sorry, it took me some time to update.
I updated node-red and nodejs as you recommended. After the update, version ui_level 0.0.24 was installed. With this version, the bars worked correctly. Then I updated ui_level to version 0.1.28 - and  everything works also fine with all output devices and browsers. Unfortunately I cannot say if the nodered-update or ui_level version 0.1.28 were responsible for the improvement.
Nevertheless, thanks for your immediate help and recommendations.
Best regards
Gerhard

**Comment by hotNipi** [comment]
Nice. But with your help I managed to ui_level also work again with the Edge browser. 
Thanks a lot :). Case closed

**Comment by gerhard1951** [comment]
Just for your information: I tested the dual level mode.  Now, the top bar shows always full length independent of the actual value, the bottom bar shows the right value. But only on my Android devices with Firefox. 

On an Android device  with Chrome browser and on my Windows PC with Firefox it works correctly. 

 

Best regards

Gerhard

 

Von: hotNipi <notifications@github.com> 
Gesendet: Freitag, 15. Mai 2020 18:54
An: hotNipi/node-red-contrib-ui-level <node-red-contrib-ui-level@noreply.github.com>
Cc: gerhard1951 <mail@ge-benker.de>; State change <state_change@noreply.github.com>
Betreff: Re: [hotNipi/node-red-contrib-ui-level] Horizontal Level always displayed as "Max" - again (#23)

 

Closed #23 <https://github.com/hotNipi/node-red-contrib-ui-level/issues/23> .

**Comment by hotNipi** [comment]
v0.1.29 has fix for dual mode. It was me not testing all layouts after previous fix was applied.
