### ISSUE TITLE
Make width of bar configurable

### ISSUE THREAD

**Issue by jeroenst** [hotNipi/node-red-contrib-ui-level#26]
**Is your feature request related to a problem? Please describe.**
I would like a wider level bar

**Describe the solution you'd like**
A configuration option to specify the width of the level bar

**Describe alternatives you've considered**
Changing CSS (did not work)

**Additional context**

**Comment by hotNipi** [comment]
Hi, 
Thank you for your interest and contribution. I see that your requests are somehow connected. 
Make bar size configurable and remove tickmarks. Can you describe more clearly (or may be sketch) what the widget should do for you. Even it is complicated, the option to consider may be that bar will fulfill whole widget area if let's say all text options are turned off at configuration page. Just to make bar wider will be hard many things go wrong with text sizes. (devices tend to lie about sizes) 
Or perhaps whole new layout? Suggestions welcome!

Let's take all discussion in here and make decisions about other (seems to me connected) requests afterwards

**Comment by jeroenst** [comment]
I will make these changes and will make some pull requests when finished.
