### ISSUE TITLE
Option to NOT have minimum and maximum ticks in bar colorized

### ISSUE THREAD

**Issue by Nodi-Rubrum** [hotNipi/node-red-contrib-ui-level#28]
Option to NOT have minimum and maximum ticks in bar colorized.

Any way to not have ui-level colorize the minimum and maximum ticks in the bar? Not understanding why they are colorized when the value is zero.

**Comment by hotNipi** [comment]
Not sure I'm understand correctly.
![image](https://user-images.githubusercontent.com/35291460/91631391-de9d8500-e9e1-11ea-9769-9926b2c5326e.png)

If you mean that with with minimum (or less than minimum) value, some "leds" are active, than that is how most of similar real world indicators work. And yes there is another approach - no active leds if value is minimum or bellow. 

Why I decided to take the first approach? 
Well, that was then what I liked most. It shows more clearly that the widget is working well. By that I mean that if you come and look your dashboard at first glance - you should be able to determine conditions of the elements fast and seamlessly. That way there is no doubts that widget works. Just value is what it is at this moment.
  
Can it be configurable? If there will be reasonable explanations why there should be that option, then it is possible. But for now it does not seems to me necessary. 

But if it is not what you mean, please explain a little more. May be some images or so...

**Comment by Nodi-Rubrum** [comment]
Ah, thanks for the details, appreciated.  Oh, and your approach makes a lot of sense, this was designed to mimic what a typical audio signal processor often displays right?  I was thinking I could abuse it... to be a vertical progress bar.  But that was definitely taking control out of the design scope, true.  If I could hide the max/min values, I would abuse it, so to speak.  :)
