### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by Just-another-pleb** [hotNipi/node-red-contrib-ui-level#29]
I was wanting to use this to indicate the level of charge in a battery.

Only a small part of the screen.  1 x 1.

But I can't get rid of the actual value being shown on top of the graph.

![Screenshot from 2020-10-28 06-51-19](https://user-images.githubusercontent.com/39888280/97354992-5e64a480-18ea-11eb-99ff-75a567cb81be.png)
I get that they may be needed sometimes, but I think it is a bug (sorry if it is a feature request) as there isn't an option to turn the text/value being displayed off.

**Comment by hotNipi** [comment]
There is options for such kind of setup.
Leave the "Label" field empty and check "Hide value field"
![image](https://user-images.githubusercontent.com/35291460/97355766-0c972c80-18a0-11eb-9a84-e0b77562aa52.png)

**Comment by Just-another-pleb** [comment]
Ah, stupid me.

I guess that they were so far apart on the screen may have contributed to
me not associating them.

My bad.

**Comment by hotNipi** [comment]
I think it is just too many options for this node. But what can I do....
