### ISSUE TITLE
Remove warning "Couldn't reach to the site parameters. Using defaults"

### ISSUE THREAD

**Issue by CopyCat73** [hotNipi/node-red-contrib-ui-level#3]
It keeps popping up in my log each time I deploy. It seems that it checks for some kind of global settings but your documentation does not mention anything. I try my best to have a clear log and at this point the warning does not make any sense ;)

**Comment by hotNipi** [comment]
This is an issue I try to resolve but seems to not happen in all systems and setups.
Please add info about your setup. 
OS/Platform version
Nodejs version
Node-red version
Dashboard version

Thank you

**Comment by hotNipi** [comment]
Issue is that node-red-dashboard custom widgets API does node expose site properties. It is discussed and it will be probably added soon. After that dashboard improvement I can fix this issue inside ui_level node also. 
See topic in Node-RED forum
https://discourse.nodered.org/t/how-to-retrieve-site-sizes-from-my-custom-node-source-code/9681/4

**Comment by hotNipi** [comment]
Fix will be after node-red-dashboard next release (current version is 2.14.0) I will state that out in forum when it happened.

**Comment by hotNipi** [comment]
Warning is replaced with node.log call in version 0.0.13
You will see it in terminal window if issue happened but not in editor debug window (if default configuration for log level in use).    

Version 0.0.13 is fully prepared to next release of node-red-dashboard where site properties are exposed for custom ui-widgets. No need to update ui_level node after dashboard update.

Closing this issue with this.
