### ISSUE TITLE
Which part of the message is used.

### ISSUE THREAD

**Issue by Just-another-pleb** [hotNipi/node-red-contrib-ui-level#30]
Going on from my other "bug report" I now also see that `msg.payload` is the only thing that can be used to give it a value.

That's ok for most times, but now I have to modify my flows as `msg.payload` is used for something else.
~~(Ironically I believe the other node can have its input qualifier changed, so all is kind of good)~~

I spoke too soon.
So now I'm stuck.

**Comment by hotNipi** [comment]
It can be added. 
Expect an update soon

![image](https://user-images.githubusercontent.com/35291460/97357926-2dad4c80-18a3-11eb-8a89-3a1d5c4cbe73.png)

**Comment by hotNipi** [comment]
Supported with version 0.1.36 (available as soon the indexing of npm is done)

**Comment by Just-another-pleb** [comment]
Thanks.

Appreciated.
