### ISSUE TITLE
on max value when displayed until first refresh

### ISSUE THREAD

**Issue by lemny** [hotNipi/node-red-contrib-ui-level#31]
Since the update to 0.1.37 the bars are always at max value until they are refreshed with a new value while displayed.
The numbers are shown correctly, but the bars are always completely full when just shown.

Using Dashboard of Node Red 1.1.3.

**Comment by hotNipi** [comment]
I need info/versions about the device and browser where dashboard runs.

**Comment by lemny** [comment]
PC - Windows 10 - Chrome / Edge
iPad - iOS14 - Safari

ah... and i double checked... it happens not after reloading the page, but every time I switched the tabs within the dash board.

**Comment by hotNipi** [comment]
You are correct. Issue fixed. v0.1.38 will be available shortlly.
