### ISSUE TITLE
Zero Reference - Center Swing point for +ve and -ve ui level

### ISSUE THREAD

**Issue by G-Cottam** [hotNipi/node-red-contrib-ui-level#32]
The Min and Max are settable however the zero reference is not.  It always assumes a positive number from minimum when displaying the levels, It would be good to have the ability to set the zero reference so the ui levels swings from this zero reference point.

This would allow this to be used for display of a controllers output eg Possitive or Negative Controller output. with Zero Center.
Or Delta from Setpoint display.

The levels could then peek in both directions away from the zero reference point.

The Zero reference at first could be "0" for first version but actualy the same maths would work if it was changed to be from a reference number "number" for delta from setpoint.

Love the ui Level, good job !!.

**Comment by hotNipi** [comment]
The support for differential mode is asked many times.  But there is design flaw written into ui_level which takes almost rewrite whole node to get rid of first. Too much work to fit into my daily schedules. 
But there is a next generation of the artless-gauge which supports dashed lines now, so it can be configured to look similar to ui_level. And for artless-gauge, the differential mode is fully supported.

![image](https://user-images.githubusercontent.com/35291460/100536468-7735e200-3229-11eb-8d8e-e9531a908902.png)

**Comment by rohnershare** [comment]
Hello I am unfortunately a complete beginner in programming. however, I would like to build a dashboard in node red. I've seen your bar graphics and I think they're very beautiful. I would like to have everything (as far as possible) automated in my project. to do this, I transfer the variables using payload. now i would like to build a block that is predefined. unfortunately I can't quite get along with your code. I am also working on the project with a friend and although he can program well, he cannot cope with it either. if you want you can write to me at beschlac@gmail.com then I can explain it to you in more detail. I would be very happy. Greetings from the black forest, bernd

**Comment by hotNipi** [comment]
I did read couple of times but still I don't understand the problem.
But I guess You are trying to do custom widget for node-red dashboard. If so, my nodes are not best example for beginners for sure. They are complex mainly due the too many options offered with one node but also my intention is to keep calculations at server side to have front-end power more dedicated to rendering.  That makes code hard to read and understand. But not my fault.

But anyway. You should open your problem more clearly.

**Comment by hotNipi** [comment]
Closed due the inactivity
