### ISSUE TITLE
Bug with msg.control.seg

### ISSUE THREAD

**Issue by lucasth24** [hotNipi/node-red-contrib-ui-level#33]
**Describe the bug**
When trying to set the Min and Max values using the msg.control.seg1/2, it doesn't really change the value, only the label of it. 
I need to input a variable value inside that min/max. Im trying to do it thru msg.control but here what happens:

**To Reproduce**
With the inside-node configuration all goes well:
![image](https://user-images.githubusercontent.com/67165075/101680797-fa341500-3a3f-11eb-8649-a26592d37fc5.png)
this is what happens (and how i need it to be):
![image](https://user-images.githubusercontent.com/67165075/101680945-2cde0d80-3a40-11eb-92ff-d3773302b281.png)

With msg.control.seg1 and msg.control.seg2:
![image](https://user-images.githubusercontent.com/67165075/101681122-72023f80-3a40-11eb-8f67-1e102eb8c335.png)
here is the bug:
![image](https://user-images.githubusercontent.com/67165075/101681216-96f6b280-3a40-11eb-9be9-28b5bfa8d362.png)

Great work by the way!!

**Environment and versions**
 - OS: windows 10
 - Microsoft Edge
 - Node-RED version: 1.1.3
 - Dashboard version: 2.24.2
 - ui-level version: 0.1.38

**Comment by hotNipi** [comment]
You were correct. Happens with "single color bar" option  selected. 
Fixed in v0.1.39
Thank you for reporting the issue.
