### ISSUE TITLE
Show current value as a node status 

### ISSUE THREAD

**Issue by My-Random-Thoughts** [hotNipi/node-red-contrib-ui-level#35]
Can you add an option to show the currently displayed value as the node status
(https://nodered.org/docs/creating-nodes/status) 

It will allow people to quickly see the value being shown on the dashboard without actually loading the dashboard.

Just an idea, thank you.

**Comment by hotNipi** [comment]
Fair enough. May be the status should be  Label + value + unit

![image](https://user-images.githubusercontent.com/35291460/119861971-abf8cc80-bf20-11eb-9ff6-6c89dbb54411.png)

**Comment by My-Random-Thoughts** [comment]
Yea, looks good.  Thanks

**Comment by hotNipi** [comment]
v0.1.43 should be available for now.
