### ISSUE TITLE
Updating Min/Max does not refresh ticks 

### ISSUE THREAD

**Issue by SaKiEQ** [hotNipi/node-red-contrib-ui-level#37]
**Describe the bug**
when sending msg.control to update min/mx values, the tick marks remain based on the manual
values entered in the config panel. They do not seem to refresh or change one a message is sent.

**Expected behavior**
Tick values, specially if left on Auto mode should refresh when msg.config { min / max} is sent.

**Environment and versions (please complete the following information):**
 - OS: OS X:  10.15
 - Browser: Safari
 - Node-RED:  1.3.5
 - Dashboard version (good question... next question ? ) 
 - ui-level version: 0.1.44

**Comment by SaKiEQ** [comment]
![Screen Shot 2021-08-23 at 9 24 33 PM](https://user-images.githubusercontent.com/35499064/130515621-c7c20742-6fb0-41b1-b65f-35425df32750.jpg)
You see the left of the three vertical bars, look at the max / min values vs. the tick mark values. 

The default setting of the widget is 0 - 2000 units, but a function scales the min/max via msg.control during run time. 
The ticks do not seem to react to any value change on max/min, or seg1/seg2 changes. 

I assume they use the hard coded references to the widgets defaults ?

**Comment by hotNipi** [comment]
For auto mode considered as bug and will be fixed
But if set for segments, it still stays as user responsibility to set new values via control message.

**Comment by SaKiEQ** [comment]
Yeah its in auto mode... since the min/max change dynamically to have more resolution / latitude in the level bar. I try to keep the actual value window as small as possible to see the deviation from the value better. Hence the min/max are with each level change newly computed and updated. 

The config min/max values do not change on msg.control{min: max:}, they remain the manually set values. From what I can see in the code, its those 'defaults' are used to build the tick labels in auto mode, not the msg.control values.

**Comment by hotNipi** [comment]
update available.

**Comment by SaKiEQ** [comment]
Works like a charm :) Many Thanks !
