### ISSUE TITLE
No bar displayed

### ISSUE THREAD

**Issue by ghost** [hotNipi/node-red-contrib-ui-level#40]
**Describe the bug**
Today I tried to use the ui-level but I don't see the bar .....

![aaa](https://user-images.githubusercontent.com/81916825/151006239-63b95f10-9366-4373-9ade-0221322417d4.png)

**Environment and versions (please complete the following information):**
Ubuntu 20.04
Firefox 96.0
Node-RED version: v2.1.6
Node.js  version: v14.16.0
Dashboard version 3.1.3
ui-level version 0.1.46

Can you help me?

**Comment by hotNipi** [comment]
As I don't have ubuntu available to test, I can't do much. 
Do you see any errors in browser console log?

**Comment by ghost** [comment]
This can help you?

![bbbb](https://user-images.githubusercontent.com/81916825/151139367-7791a9d0-205c-41dc-9e0f-c27a4d1ed600.png)

**Comment by hotNipi** [comment]
This all seems fine. 
Try clear browser cache. Sometimes it helps...

**Comment by ghost** [comment]
I deleted browser cache, nothing's changed ...

Level has this problem, but Node artless-gauge works fine  ... is useful?

**Comment by ghost** [comment]
Well, I changed dashboard and now Level works fine ....

**Comment by hotNipi** [comment]
Strange but if working now nothing more to dig into also :)
