### ISSUE TITLE
Numbers and digits without the bars.

### ISSUE THREAD

**Issue by WillemBrx** [hotNipi/node-red-contrib-ui-level#41]
This node is great. I would love to see the same node but without the bars showing. Numbers (and label) only. Do you think that is possible?

Kind regards,

William

**Comment by hotNipi** [comment]
Well, showing just a value (with unit added maybe) is kind of simple task which can be achieved with native dashboard elements like ui_text node or if something more fancy needed then ui_template node where you can decorate things with CSS. 
Can't really see any reason to add such configuration options for this node. It is kind of over-complicated already.

**Comment by WillemBrx** [comment]
You were absolutely right! Never knew of this option!

Kind regards,

Willem Brakenhoff

________________________________
Van: hotNipi ***@***.***>
Verzonden: Thursday, February 3, 2022 9:47:38 AM
Aan: hotNipi/node-red-contrib-ui-level ***@***.***>
CC: WillemBrx ***@***.***>; Author ***@***.***>
Onderwerp: Re: [hotNipi/node-red-contrib-ui-level] Numbers and digits without the bars. (Issue #41)


Well, showing just a value (with unit added maybe) is kind of simple task which can be achieved with native dashboard elements like ui_text node or if something more fancy needed then ui_template node where you can decorate things with CSS.
Can't really see any reason to add such configuration options for this node. It is kind of over-complicated already.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FhotNipi%2Fnode-red-contrib-ui-level%2Fissues%2F41%23issuecomment-1028736081&data=04%7C01%7C%7C1768bb421e55476d16fb08d9e6f1d588%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794748603538843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Razg7n%2BdBs5318aIEg0NE7X3596SSICOGVcTizb6RK8%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXSGCC725VC2CFFSL2KHMULUZI6KVANCNFSM5NOIN6KA&data=04%7C01%7C%7C1768bb421e55476d16fb08d9e6f1d588%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794748603538843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P9bDZu4%2BxzVF21hu5hqz%2F%2Bxa0%2BaDv2LgF%2FxgNrFVCaU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1768bb421e55476d16fb08d9e6f1d588%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794748603538843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IAAWwkQbFS5C%2Fd0OwtJWFxzFlea7cBEqC%2FR1xtPv6Is%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1768bb421e55476d16fb08d9e6f1d588%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794748603538843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fyWyvUI%2BX%2By2W1J1cwPPGg9OGixOKgAdYrtVumdNEaM%3D&reserved=0>.
