### ISSUE TITLE
Propper Display Option for Celcius/Fahrenheit

### ISSUE THREAD

**Issue by matthiasbaldi** [hotNipi/node-red-contrib-ui-level#46]
**Is your feature request related to a problem? Please describe.**
I use the level dashboard component for different things.
One case is for battery states for shellies another use case is for temperature values from the i.e. heatpump or Netatmo devices.
It is possible to feed the data in but when it comes to temperature values in Celcius or Fahrenheit it would be nice to have a center for 0°C or 32°F and then the color goes up or down (i.e. from green into red shapes up and into blue shapes down).

**Describe the solution you'd like**
It would be nice to get a 4th option in the layout to choose "temperature" and then to configure the min and max values as it is.

**Describe alternatives you've considered**
All the other projects I found around are not that beautiful as yours is.
And when it is too complicated to integrate that feature directly in the same node, maybe there is an option to create a dedicated temperature node for it.

Thank you - you have a great lib 👌💪

**Comment by hotNipi** [comment]
The differential mode is implemented with my other gauge - the artless gauge. But for this node it is not possible. The way it is created just does not allow such design graphically.

**Comment by matthiasbaldi** [comment]
Thank you @hotNipi 
That looks very promising. I think then I will use your other node to visualize the temperature.
But a gradient would be also nice 😉
