### ISSUE TITLE
Disable Stripes

### ISSUE THREAD

**Issue by jeroenst** [hotNipi/node-red-contrib-ui-level#49]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The bargauges are always deviced by stripes, I would like to set stripes to off so a continuous bar is displayed.

So from this:

![image](https://github.com/user-attachments/assets/4e18d805-2b4f-41ad-9d71-6dff7026e558)

To this:

![image](https://github.com/user-attachments/assets/82417411-addc-4aa5-a33c-62b0cf82fe1a)

For both horizontal and vertical bars.

**Describe alternatives you've considered**
I tried overriding with CSS but had no good luck

**Additional context**

**Comment by jeroenst** [comment]
@hotNipi is there any change you can make this change?

**Comment by hotNipi** [comment]
No. This node will not get any new features. The Dashboard itself is considered to be deprecated.

**Comment by jeroenst** [comment]
Will there be a new version for the new dashboard? (Although I still use the old dashboard and it is lots of work to migrate to the new dashboard)

**Comment by hotNipi** [comment]
https://flows.nodered.org/node/@flowfuse/node-red-dashboard

And yes, it is quite of work to migrate. Not my fault I'd say :)

**Comment by jeroenst** [comment]
Okay, can you make the disable stripes functionality for the ui-level in the new dashboard instead?

**Comment by hotNipi** [comment]
That's different node thus feature request should be rise against it. https://github.com/hotNipi/node-red-dashboard-2-ui-gauge-linear

**Comment by jeroenst** [comment]
Done, thank you
